apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-__RUNTIME__-__CPU_NAME__
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: docker.io/__DOCKER_USER__/fibonacci-__RUNTIME__:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "__CPU__"
